// reg-lab-finder — 규제·시험·기관 지식 베이스
// 주의: 아래 데이터는 조사 출발점을 위한 참고 정보(INTERPRETATION)이다.
// 실제 시험 의뢰 전 반드시 규제 원문과 기관의 공식 인정 Scope(A등급 출처)를 확인할 것.

const REG_DATA = {
    updated: "2026-08-07",

    markets: [
        { id: "EU", label: "🇪🇺 EU" },
        { id: "KR", label: "🇰🇷 한국" },
        { id: "US", label: "🇺🇸 미국" },
    ],

    // 제품 특성 플래그
    flags: [
        { id: "electronic", label: "전기전자제품" },
        { id: "battery", label: "배터리 포함" },
        { id: "wireless", label: "무선기능 포함" },
    ],

    regulations: [
        {
            id: "eu-rohs",
            name: "EU RoHS",
            market: "EU",
            lawRef: "Directive 2011/65/EU + (EU) 2015/863",
            summary: "전기전자제품 내 유해물질 10종(Pb, Cd, Hg, Cr6+, PBB, PBDE, DEHP, BBP, DBP, DIBP) 함유 제한. CE 표시 대상.",
            testNeed: "common",
            testNeedLabel: "시험이 일반적인 입증방법 (자기적합선언 — Module A, 제3자 시험 법적 필수 아님)",
            match: { markets: ["EU"], anyFlags: ["electronic"] },
            requirements: [
                {
                    name: "유해물질 함유 제한",
                    detail: "균질물질 기준 Pb·Hg·Cr6+·PBB·PBDE·프탈레이트 4종 각 0.1 wt%, Cd 0.01 wt% 이하",
                    testItems: "유해물질 10종 스크리닝·정량분석",
                    standards: "IEC 62321 시리즈",
                    methods: "XRF 스크리닝 / ICP-OES / GC-MS 등",
                    bodyQual: "ISO/IEC 17025 인정 (인정 Scope에 IEC 62321 포함 여부 확인 필요)",
                },
                {
                    name: "기술문서·EU 적합성선언(DoC)",
                    detail: "EN IEC 63000 기반 기술문서 작성 및 자기적합선언",
                    testItems: "문서 검토 (시험성적서는 근거자료로 활용)",
                    standards: "EN IEC 63000",
                    methods: "기술문서 평가",
                    bodyQual: "제조자 자체 수행 가능",
                },
            ],
            links: [
                { label: "지침 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32011L0065" },
                { label: "EU Commission — RoHS", url: "https://environment.ec.europa.eu/topics/waste-and-recycling/rohs-directive_en" },
            ],
        },
        {
            id: "eu-reach",
            name: "EU REACH",
            market: "EU",
            lawRef: "Regulation (EC) No 1907/2006",
            summary: "화학물질 등록·평가·허가·제한. 완제품(Article)은 SVHC 정보전달 의무(제33조)와 부속서 XVII 제한물질 준수가 핵심.",
            testNeed: "common",
            testNeedLabel: "공급망 정보로 대응 가능한 경우가 많음 — 시험은 일반적인 입증·확인 방법",
            match: { markets: ["EU"], anyFlags: [] },
            requirements: [
                {
                    name: "SVHC 함유 정보전달 (제33조)",
                    detail: "후보목록 SVHC가 완제품 내 0.1 wt% 초과 시 수요자 정보제공, SCIP DB 신고",
                    testItems: "SVHC 함유 여부 확인 (공급망 자료 또는 분석)",
                    standards: "물질별 분석법 (통일된 단일 표준 없음)",
                    methods: "GC-MS / LC-MS / ICP 등 물질별 상이",
                    bodyQual: "ISO/IEC 17025 인정 화학분석기관 (해당 물질 분석이 Scope에 있는지 확인)",
                },
                {
                    name: "부속서 XVII 제한물질",
                    detail: "카드뮴, 니켈 용출, 프탈레이트, 납 등 품목별 제한 조건 준수",
                    testItems: "제한 항목별 함량·용출 시험",
                    standards: "예: EN 1811(니켈 용출), EN 14372(프탈레이트) 등 항목별 표준",
                    methods: "항목별 상이",
                    bodyQual: "ISO/IEC 17025 인정 (항목별 Scope 확인)",
                },
            ],
            links: [
                { label: "규정 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02006R1907-20221217" },
                { label: "ECHA — 후보목록(SVHC)", url: "https://echa.europa.eu/candidate-list-table" },
            ],
        },
        {
            id: "eu-lvd",
            name: "EU LVD (저전압지침)",
            market: "EU",
            lawRef: "Directive 2014/35/EU",
            summary: "AC 50–1000V / DC 75–1500V 전기기기의 전기안전. CE 표시 대상.",
            testNeed: "self",
            testNeedLabel: "제조자 자기적합성평가 (Module A) — LVD에는 Notified Body 관여 모듈이 없음",
            match: { markets: ["EU"], anyFlags: ["electronic"] },
            requirements: [
                {
                    name: "전기안전 요구사항",
                    detail: "감전·화재·기계적 위험 등 안전목표 충족. 정합표준 적용 시 적합성 추정",
                    testItems: "절연·내전압·온도상승·이상동작 등 안전시험",
                    standards: "EN IEC 62368-1(AV·ICT기기), EN 60335 시리즈(가전) 등 제품군별 정합표준",
                    methods: "안전시험 설비 (내전압시험기 등)",
                    bodyQual: "법적으로는 제조자 자체시험 가능 — 실무상 ISO/IEC 17025 인정기관 성적서 활용이 일반적",
                },
            ],
            links: [
                { label: "지침 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014L0035" },
                { label: "LVD 정합표준 목록 (EU Commission)", url: "https://single-market-economy.ec.europa.eu/single-market/european-standards/harmonised-standards/low-voltage-lvd_en" },
            ],
        },
        {
            id: "eu-emc",
            name: "EU EMC 지침",
            market: "EU",
            lawRef: "Directive 2014/30/EU",
            summary: "전자파 방출·내성 요구. CE 표시 대상.",
            testNeed: "self",
            testNeedLabel: "제조자 자기적합성평가 가능 — Notified Body 관여(Module B)는 선택사항",
            match: { markets: ["EU"], anyFlags: ["electronic"] },
            requirements: [
                {
                    name: "전자파 방출(Emission)·내성(Immunity)",
                    detail: "타 기기에 허용 불가한 전자파 장해를 주지 않고, 의도된 환경에서 정상 동작할 것",
                    testItems: "방사·전도 방출, 정전기·서지 등 내성시험",
                    standards: "EN 55032 / EN 55035(멀티미디어), EN IEC 61000-3-2/-3-3, EN IEC 61000-4 시리즈",
                    methods: "전자파 챔버, EMC 수신기 등",
                    bodyQual: "법적 필수 아님 — 실무상 ISO/IEC 17025 인정 EMC 시험소 성적서 활용이 일반적",
                },
            ],
            links: [
                { label: "지침 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014L0030" },
                { label: "EMC 정합표준 목록 (EU Commission)", url: "https://single-market-economy.ec.europa.eu/single-market/european-standards/harmonised-standards/electromagnetic-compatibility-emc_en" },
            ],
        },
        {
            id: "eu-red",
            name: "EU RED (무선기기지침)",
            market: "EU",
            lawRef: "Directive 2014/53/EU",
            summary: "무선기기의 스펙트럼 효율·EMC·안전·EMF, 그리고 제3.3조(d)(e)(f) 사이버보안 요구. CE 표시 대상.",
            testNeed: "conditional",
            testNeedLabel: "정합표준을 완전히 적용하면 자기평가 가능 — 정합표준 미적용·부분적용 시 Notified Body 필수",
            match: { markets: ["EU"], anyFlags: ["wireless"] },
            requirements: [
                {
                    name: "무선 성능 (Art. 3.2)",
                    detail: "스펙트럼의 효율적 사용, 유해 간섭 방지",
                    testItems: "출력, 주파수 점유, 스퓨리어스 방출 등",
                    standards: "EN 300 328(2.4GHz), EN 301 893(5GHz) 등 기술별 표준",
                    methods: "RF 시험설비",
                    bodyQual: "ISO/IEC 17025 인정 RF 시험소 (해당 표준 Scope 확인)",
                },
                {
                    name: "EMC·안전·EMF (Art. 3.1)",
                    detail: "EMC, 전기안전, 인체 전자파 노출 제한",
                    testItems: "EMC 시험, 안전시험, SAR/EMF 평가",
                    standards: "EN 301 489 시리즈, EN IEC 62368-1, EN IEC 62311 / EN 50566 등",
                    methods: "EMC 챔버, SAR 측정설비 등",
                    bodyQual: "ISO/IEC 17025 인정 (SAR 등은 별도 Scope 확인)",
                },
                {
                    name: "사이버보안 (Art. 3.3 d/e/f)",
                    detail: "인터넷 연결 무선기기 등의 네트워크 보호·개인정보 보호·사기 방지 — 2025-08-01부터 적용",
                    testItems: "보안기능 평가",
                    standards: "EN 18031-1/-2/-3 (일부 제한사항 있음 — 제한 해당 시 NB 관여 필요)",
                    methods: "보안 평가",
                    bodyQual: "정합표준 완전 적용 시 자기평가, 아니면 Notified Body",
                },
            ],
            links: [
                { label: "지침 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014L0053" },
                { label: "RED 정합표준 목록 (EU Commission)", url: "https://single-market-economy.ec.europa.eu/single-market/european-standards/harmonised-standards/red_en" },
            ],
        },
        {
            id: "eu-battery",
            name: "EU 배터리 규정",
            market: "EU",
            lawRef: "Regulation (EU) 2023/1542",
            summary: "배터리 및 배터리 내장 제품의 지속가능성·안전·라벨링·공급망 실사. CE 표시 대상이며 부속서 VIII 적합성평가 절차 적용(모듈에 따라 Notified Body 관여).",
            testNeed: "conditional",
            testNeedLabel: "배터리 유형·모듈에 따라 Notified Body 관여 필요 여부가 다름 — 부속서 VIII 확인 필수",
            match: { markets: ["EU"], anyFlags: ["battery"] },
            requirements: [
                {
                    name: "안전·성능·내구성",
                    detail: "휴대용 배터리 등 유형별 전기화학 성능·내구성 요구 (단계적 시행)",
                    testItems: "용량, 사이클 수명, 안전시험 등",
                    standards: "EN IEC 61960, EN IEC 62133-2(안전) 등 — 규정 이행법령·정합표준 공표 상황 확인 필요",
                    methods: "배터리 시험설비",
                    bodyQual: "적합성평가 모듈에 따름 (자기평가~NB 관여)",
                },
                {
                    name: "탄소발자국·재활용원료 함량",
                    detail: "EV·산업용 배터리 대상 탄소발자국 신고 등 (단계적 시행)",
                    testItems: "산정·검증 (시험이 아닌 검증 성격)",
                    standards: "규정 위임법령에 따른 산정방법",
                    methods: "LCA 산정·제3자 검증",
                    bodyQual: "Notified Body / 검증기관 (시행법령 확인)",
                },
            ],
            links: [
                { label: "규정 원문 (EUR-Lex)", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R1542" },
                { label: "EU Commission — Batteries", url: "https://environment.ec.europa.eu/topics/waste-and-recycling/batteries_en" },
            ],
        },
        {
            id: "kc-safety",
            name: "KC 전기용품 안전관리",
            market: "KR",
            lawRef: "전기용품 및 생활용품 안전관리법",
            summary: "전기용품을 위해도에 따라 안전인증 / 안전확인 / 공급자적합성확인 3단계로 관리. 품목별로 절차와 제3자 관여 수준이 다름.",
            testNeed: "third",
            testNeedLabel: "안전인증·안전확인 대상은 지정기관 시험 필수 — 공급자적합성확인 대상은 자체시험 또는 시험기관 성적서",
            match: { markets: ["KR"], anyFlags: ["electronic"] },
            requirements: [
                {
                    name: "안전기준 적합 (품목별)",
                    detail: "품목별 안전기준(K 표준) 적합. 안전인증 대상은 인증+정기검사, 안전확인 대상은 시험 후 신고",
                    testItems: "품목별 안전시험 (절연, 온도, 이상동작 등)",
                    standards: "KC 60335 시리즈, KC 62368-1 등 품목별 안전기준",
                    methods: "안전시험 설비",
                    bodyQual: "산업통상자원부 지정 안전인증기관·시험기관 (KTL, KTC, KTR 등 — 품목별 지정범위 확인)",
                },
            ],
            links: [
                { label: "법령 원문 (국가법령정보센터)", url: "https://www.law.go.kr/법령/전기용품및생활용품안전관리법" },
                { label: "제품안전정보센터 (안전기준·인증정보)", url: "https://www.safetykorea.kr" },
            ],
        },
        {
            id: "kc-radio",
            name: "KC 전파법 적합성평가",
            market: "KR",
            lawRef: "전파법 제58조의2",
            summary: "방송통신기자재의 적합인증 / 적합등록 / 잠정인가. 무선기기는 대부분 적합인증 또는 지정시험기관 시험 후 적합등록 대상.",
            testNeed: "third",
            testNeedLabel: "국립전파연구원(RRA) 지정시험기관의 시험 필수 (대상·절차는 고시로 확인)",
            match: { markets: ["KR"], anyFlags: ["wireless", "electronic"] },
            requirements: [
                {
                    name: "무선설비·전자파 적합성",
                    detail: "무선설비 기술기준, 전자파적합성(EMC) 기준 적합",
                    testItems: "무선 성능, EMC (방출·내성)",
                    standards: "국립전파연구원 고시 기술기준 (KS C 9832/9835 등 준용)",
                    methods: "RF·EMC 시험설비",
                    bodyQual: "RRA 지정시험기관 (기관별 지정 시험범위 확인 필수)",
                },
            ],
            links: [
                { label: "법령 원문 (국가법령정보센터)", url: "https://www.law.go.kr/법령/전파법" },
                { label: "국립전파연구원 — 적합성평가", url: "https://www.rra.go.kr" },
            ],
        },
        {
            id: "us-fcc",
            name: "US FCC (Part 15 등)",
            market: "US",
            lawRef: "47 CFR Part 15 / Part 2",
            summary: "미국 시장 전자기기의 전자파 규제. 무선(intentional radiator)은 Certification, 일반 디지털기기는 SDoC 절차.",
            testNeed: "conditional",
            testNeedLabel: "Certification 대상: FCC 인정 시험소 시험 + TCB 인증 필수 / SDoC 대상: 책임자 자기적합선언 (시험은 일반적 입증방법)",
            match: { markets: ["US"], anyFlags: ["electronic", "wireless"] },
            requirements: [
                {
                    name: "무선기기 Certification",
                    detail: "의도적 방사기기(Wi-Fi, BT 등)는 FCC ID 취득 필요",
                    testItems: "RF 출력, 대역외 방출, EMC 등",
                    standards: "47 CFR Part 15 Subpart C 등, ANSI C63.4 / C63.10 측정법",
                    methods: "RF·EMC 시험설비",
                    bodyQual: "FCC 인정(accredited) 시험소 시험 + TCB(Telecommunication Certification Body) 인증 — 법적 필수",
                },
                {
                    name: "디지털기기 SDoC",
                    detail: "비의도적 방사기기는 Supplier's Declaration of Conformity",
                    testItems: "방사·전도 방출",
                    standards: "47 CFR Part 15 Subpart B, ANSI C63.4",
                    methods: "EMC 시험설비",
                    bodyQual: "특정 시험소 자격이 법적 필수는 아님 — 실무상 인정 시험소 활용 일반적",
                },
            ],
            links: [
                { label: "규정 원문 (eCFR Part 15)", url: "https://www.ecfr.gov/current/title-47/chapter-I/subchapter-A/part-15" },
                { label: "FCC — Equipment Authorization", url: "https://www.fcc.gov/engineering-technology/laboratory-division/general/equipment-authorization" },
            ],
        },
    ],

    // 시험·검사기관 디렉터리 — 나열된 자격은 일반 현황이며,
    // 특정 시험표준의 수행 가능 여부는 반드시 공식 인정 Scope에서 확인해야 한다.
    orgs: [
        {
            id: "ktl", name: "KTL 한국산업기술시험원", country: "🇰🇷 한국", location: "진주(본원)·안산 등",
            fields: ["safety", "emc", "chem"],
            desc: "국내 대표 종합 시험인증기관. 전기안전·EMC·환경·의료기기 등 광범위한 분야 수행.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "KC 안전인증기관 (산업부 지정)", "IECEE CB 시험소", "RRA 지정시험기관"],
            url: "https://www.ktl.re.kr",
        },
        {
            id: "ktc", name: "KTC 한국기계전기전자시험연구원", country: "🇰🇷 한국", location: "군포 등",
            fields: ["safety", "emc"],
            desc: "기계·전기·전자 분야 시험인증. KC 안전인증·EMC·해외인증 지원.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "KC 안전인증기관 (산업부 지정)", "IECEE CB 시험소", "RRA 지정시험기관"],
            url: "https://www.ktc.re.kr",
        },
        {
            id: "ktr", name: "KTR 한국화학융합시험연구원", country: "🇰🇷 한국", location: "과천 등",
            fields: ["chem", "safety"],
            desc: "화학분석 강점 — RoHS·REACH 유해물질 분석, 소재·환경 시험.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "KC 안전인증기관 (산업부 지정)"],
            url: "https://www.ktr.or.kr",
        },
        {
            id: "kcl", name: "KCL 한국건설생활환경시험연구원", country: "🇰🇷 한국", location: "서울·오창 등",
            fields: ["chem", "safety"],
            desc: "생활용품·건설자재·환경 분야 시험인증.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "KC 인증 관련 지정기관"],
            url: "https://www.kcl.re.kr",
        },
        {
            id: "hct", name: "HCT (에이치시티)", country: "🇰🇷 한국", location: "이천 등",
            fields: ["emc"],
            desc: "RF·EMC 전문 민간 시험기관. 국내외 무선인증(KC·FCC·CE RED) 시험.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "RRA 지정시험기관", "FCC 인정 시험소"],
            url: "https://www.hct.co.kr",
        },
        {
            id: "dtnc", name: "DT&C (디티앤씨)", country: "🇰🇷 한국", location: "용인 등",
            fields: ["emc", "safety"],
            desc: "RF·EMC·전기안전 민간 시험기관. 국내외 인증 시험 지원.",
            quals: ["KOLAS 인정 (ISO/IEC 17025)", "RRA 지정시험기관"],
            url: "https://www.dtnc.net",
        },
        {
            id: "sgs", name: "SGS (한국법인)", country: "🌐 글로벌 (한국 시험소 보유)", location: "본사 스위스 제네바",
            fields: ["chem", "safety", "emc", "cert"],
            desc: "글로벌 시험·검사·인증기관. 유해물질 분석, 소비재, 전기전자 등.",
            quals: ["각국 인정기구별 ISO/IEC 17025 인정 (시험소별 상이)", "일부 법인 EU Notified Body"],
            url: "https://www.sgs.com",
        },
        {
            id: "tuv-rh", name: "TÜV Rheinland Korea", country: "🌐 글로벌 (한국 법인)", location: "본사 독일 쾰른",
            fields: ["safety", "emc", "cert"],
            desc: "독일계 시험인증기관. CE·국제인증, 전기안전·EMC.",
            quals: ["ISO/IEC 17025 (시험소별)", "EU Notified Body (독일 본사 등)", "IECEE CB"],
            url: "https://www.tuv.com",
        },
        {
            id: "tuv-sud", name: "TÜV SÜD Korea", country: "🌐 글로벌 (한국 법인)", location: "본사 독일 뮌헨",
            fields: ["safety", "emc", "cert"],
            desc: "독일계 시험인증기관. 제품안전·배터리·국제인증.",
            quals: ["ISO/IEC 17025 (시험소별)", "EU Notified Body (독일 본사 등)", "IECEE CB"],
            url: "https://www.tuvsud.com",
        },
        {
            id: "intertek", name: "Intertek Korea", country: "🌐 글로벌 (한국 법인)", location: "본사 영국 런던",
            fields: ["chem", "safety", "emc", "cert"],
            desc: "글로벌 시험인증기관. 소비재·전기전자·화학분석.",
            quals: ["ISO/IEC 17025 (시험소별)", "일부 법인 EU Notified Body"],
            url: "https://www.intertek.com",
        },
        {
            id: "ul", name: "UL Solutions Korea", country: "🌐 글로벌 (한국 법인)", location: "본사 미국 일리노이",
            fields: ["safety", "emc", "cert"],
            desc: "미국계 안전인증기관. UL 인증, 배터리 안전, 북미 시장 대응.",
            quals: ["ISO/IEC 17025 (시험소별)", "OSHA NRTL (미국)", "IECEE CB"],
            url: "https://www.ul.com",
        },
        {
            id: "bv", name: "Bureau Veritas Korea", country: "🌐 글로벌 (한국 법인)", location: "본사 프랑스 파리",
            fields: ["chem", "safety", "cert"],
            desc: "프랑스계 시험·검사·인증기관. 소비재·산업검사.",
            quals: ["ISO/IEC 17025 (시험소별)", "일부 법인 EU Notified Body"],
            url: "https://www.bureauveritas.com",
        },
    ],

    orgFields: [
        { id: "safety", label: "전기안전" },
        { id: "emc", label: "EMC·RF" },
        { id: "chem", label: "화학분석" },
        { id: "cert", label: "인증기관" },
    ],

    // A등급 공식 데이터베이스 — 기관 자격·Scope 검증용
    officialDbs: [
        { name: "KOLAS 한국인정기구", desc: "국내 공인시험·교정기관 인정 현황 및 인정 Scope 검색", url: "https://www.kolas.go.kr" },
        { name: "EU NANDO", desc: "EU Notified Body 지정 현황·지정범위 공식 DB", url: "https://webgate.ec.europa.eu/single-market-compliance-space/#/notified-bodies" },
        { name: "IECEE CB Scheme", desc: "CB 인증기관(NCB)·CB 시험소(CBTL) 및 인정범위 검색", url: "https://www.iecee.org" },
        { name: "ILAC", desc: "국제시험소인정협력체 — MRA 서명 인정기구 목록", url: "https://ilac.org" },
        { name: "IAF CertSearch", desc: "경영시스템 인증 유효성 검증 DB", url: "https://www.iafcertsearch.org" },
        { name: "FCC Equipment Authorization", desc: "FCC 인정 시험소·TCB 검색, FCC ID 조회", url: "https://www.fcc.gov/engineering-technology/laboratory-division" },
        { name: "제품안전정보센터 (safetykorea)", desc: "KC 안전인증·안전확인 인증정보 및 지정기관 조회", url: "https://www.safetykorea.kr" },
        { name: "국립전파연구원 (RRA)", desc: "전파법 적합성평가 지정시험기관·적합성평가 정보", url: "https://www.rra.go.kr" },
        { name: "e나라 표준인증", desc: "국가표준(KS)·기술기준·인증제도 통합 검색", url: "https://www.standard.go.kr" },
        { name: "EUR-Lex", desc: "EU 법령 원문 공식 DB", url: "https://eur-lex.europa.eu" },
        { name: "ECHA", desc: "유럽화학물질청 — SVHC 후보목록, 제한물질", url: "https://echa.europa.eu" },
    ],

    // 매핑표 판단 단계
    verdicts: [
        { id: "confirmed", label: "확인", desc: "공식 인정 Scope에서 시험항목·표준을 직접 확인함" },
        { id: "partial", label: "부분확인", desc: "기관 공식 서비스로는 확인되나 인정 Scope까지는 미확인" },
        { id: "unverified", label: "미확인", desc: "수행 가능성을 객관적으로 확인하지 못함" },
    ],
};
